### ISSUE TITLE
Moderation feature doesn't work as designed

### ISSUE THREAD

**Issue by theguestfb** [fictionbranches/fb#18]
Tested the moderation feature by fixing a typo in an old episode. Even though it wasn't approved, the episode changed anyway. When I rejected the change, it stayed changed anyway. Also, it didn't highlight the differences between old and new. It should show both.

**Comment by fictionbranches** [comment]
Bug fixed. Correct modqueue mechanics are explained [here](https://github.com/fictionbranches/fb/blob/master/fb/optfb/static_snippets/modhelp.md)
