### ISSUE TITLE
Jump to episodes

### ISSUE THREAD

**Issue by brayn1701** [fictionbranches/fb#24]
Ability to have a link jump to an existing episode. To allow for a story to branch off sideways and return to a main root later.

Should be an FB3 feature request.

**Comment by fictionbranches** [comment]
Not sure exactly what is meant by this. Authors can already link to anything they want, including other episodes, using Markdown hyperlinks. How would this be different?

**Comment by brayn1701** [comment]
In the proposal, a jump sideways to another episode would be treated as a link from an episode.

**Comment by fictionbranches** [comment]
This sounds very messy and confusing.

**Comment by fictionbranches** [comment]
After further thought, there's not really any way to implement this that isn't pretty hacky. 

If an author wants to link their episode to an episode in a different branch, they can do so using an in-story markdown link.
