### ISSUE TITLE
New rating system format

### ISSUE THREAD

**Issue by brayn1701** [fictionbranches/fb#25]
New rating system to replace numbers scheme. Thumbs up for ratings. 

Was suggested having thumbs down for disliked and an enforced comment requirement, but that may simply be a nuisance.

Ratings system was to be coupled with viewcount for episodes. 

FB3 feature request.

**Comment by fictionbranches** [comment]
Upvotes and viewcounts have been added. Pages listing the top few of each of those are coming soon.
