### ISSUE TITLE
Add user avatars

### ISSUE THREAD

**Issue by fictionbranches** [fictionbranches/fb#4]
Give users the ability to create and modify a markdown section on their user page, above their list of episodes.

**Comment by fictionbranches** [comment]
Also add the ability to set avatars by providing a link to an image

**Comment by fictionbranches** [comment]
User bios have been implemented

**Comment by theguestfb** [comment]
You could always go third-party and use gravatar. It stores avatar images for WordPress and other platforms. Could be a quick and dirty solution.

**Comment by fictionbranches** [comment]
User avatars have been implemented, may be upgraded in the future to something more robust
